logo = "/logo.svg"
logo_small = "/logo.svg"
cover = "https://picsum.photos/1000/1000"
crafted_email_url = "mailto:05_cod_chimp@icloud.com"

styletitle = "<b><span class='text-red'>Extra</span>ordinary<span class='text-red'>IS</span></b>"

meta_description = "ExtraordinaryIS - A Movement by the Otis and Rosie Brown Foundation"
meta_keywords = "extraordinaryis,foundation,otis and rosie brown,nonprofit,501(c)(3),arlington,texas,scholarships,orbf,movement"
meta_twitter_card = "summary_large_image"
meta_twitter_site = "@YExtraordinary"
meta_twitter_creator = "@YExtraordinary"

